### ISSUE TITLE
Update preview images

### ISSUE THREAD

**Issue by sgoudham** [catppuccin/dunst#7]
## Description

This port was created before the new template for Catppuccin repositories was defined, it would be nice to update the README to have individual preview images as seen in [catppuccin/template](https://github.com/catppuccin/template?tab=readme-ov-file#previews).

This work will involve:

1. Setting up Dunst and applying the Catppuccin theme to it as per the instructions in the repository
2. Taking 4 individual screenshots of a Dunst notification, in each Catppuccin flavour (latte, frappe, macchiato and mocha)
3. Converting those images to `.webp` and storing them in the `assets` folder.
4. Generating a combined preview image via [catppuccin/catwalk](https://github.com/catppuccin/catwalk).
5. Updating the README to include the new Previews section with the new images.

## Acceptance Criteria

- The README contains a "Previews" section underneath the main preview image and above the "Usage" section, as shown in the [template](https://github.com/catppuccin/template?tab=readme-ov-file#previews).
- There are 4 individual previews in the `assets` folder, with the names `latte.webp`, `frappe.webp`, `macchiato.webp` and `mocha.webp`
- There is 1 combined preview image in the `assets` folder, named `preview.webp` which is an image generated by [catppuccin/catwalk](https://github.com/catppuccin/catwalk)

**Comment by bonswouar** [comment]
Seeing this issue is almost 9 months old and nobody has volunteered since, I wouldn't mind giving it a try!
What should be in the notification though? Let me know if you have any suggestion

_Meanwhile if you can merge https://github.com/catppuccin/dunst/pull/11 it would be great :)_

**Comment by sgoudham** [comment]
It would be great to get this issue closed, thanks for your interest! @bonswouar 

I think the notification text on the existing preview image on the README is actually pretty good and has a little bit of personality to it. 

Feel free to request me for a review on the eventual PR.

**Comment by bonswouar** [comment]
I couldn't find the original icon used in the README, but I've used the "pride" one meanwhile

Before I make a PR let me know if some changes are needed :)

![dunst_mocha_critical](https://github.com/user-attachments/assets/8bbd9c71-1cc1-4de6-af75-8378bebd112d)
![dunst_mocha](https://github.com/user-attachments/assets/917008bd-c33e-453f-b0d7-83352290b1ba)
![dunst_macchiato_critical](https://github.com/user-attachments/assets/21113918-4f52-4c23-b21c-4f3e6b2f1ee0)
![dunst_macchiato](https://github.com/user-attachments/assets/99032a9b-0bf0-4858-a802-c1d78b8d8070)
![dunst_latte_critical](https://github.com/user-attachments/assets/04a2e989-ade6-405a-b39d-699c171bcc7f)
![dunst_latte](https://github.com/user-attachments/assets/90f43e88-1e0f-4c83-aa3c-2aa5eab7f587)
![dunst_frappe_critical](https://github.com/user-attachments/assets/31b3cb58-770c-44b8-a666-7aae0f8e0c4a)
![dunst_frappe](https://github.com/user-attachments/assets/2b3387ea-626f-4915-8c07-60fe807e21f2)

**Comment by sgoudham** [comment]
Ah sorry, I should have clarified. The logo used in the existing previews is over 2 years old now and we've rebranded since then. You should use the icon stored in [catppuccin/catppuccin](https://github.com/catppuccin/catppuccin/blob/main/assets/logos/exports/1544x1544_circle.png).

I also forgot that the text would be different across both notifications so I think just the image with "Welcome To Catppuccin" is fine for the preview.

PR should be good after implementing my above comments ^ @bonswouar
